baseURL = "https://novatec.cr/"
languageCode = "es-cr"
title = "Novatec Industrial"
theme = "novatec"

[taxonomies]
  industria = "industrias"
  marca = "marcas"
  familia = "familias"

[[menu.principal]]
    name = "Industrias"
    weight = 400
    identifier = "industrias"
    url = "/industrias/"

[[menu.principal]]
    name = "Marcas"
    weight = 300
    identifier = "marcas"
    url = "/marcas/"

[[menu.principal]]
    name = "Familias"
    weight = 500
    identifier = "familias"
    url = "/familias/"
