baseURL = "https://www.novatec.cr/"
languageCode = "es-cr"
title = "Novatec Industrial"
DefaultContentLanguage = "es"

#CUSTOM PARAMS
[params]
  cloudinary_url = "https://res.cloudinary.com/novatec/image/upload/"

#Taxonomy names with forwign characters
preserveTaxonomyNames = true

[context.deploy-preview.environment]
  HUGO_VERSION = "0.42.2"
