baseURL = "https://www.novatec.cr/"
languageCode = "es-cr"
title = "Novatec Industrial"
theme = "novatec"
DefaultContentLanguage = "es"

#CUSTOM PARAMS
[params]
  cloudinary_url = "https://res.cloudinary.com/novatec/image/upload/"

#Taxonomy names with forwign characters
preserveTaxonomyNames = true

[context.deploy-preview.environment]
  HUGO_VERSION = "0.42.2"

[taxonomies]
  industria = "industrias"
  marca = "marcas"
  familia = "familias"
  subfamilia = "subfamilias"
  ncmarca = "ncmarcas"

[[menu.principal]]
    name = "Industrias"
    weight = 300
    identifier = "industrias"
    url = "/industrias/"

[[menu.principal]]
    name = "Marcas"
    weight = 400
    identifier = "marcas"
    url = "/marcas/"
