---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
  content/productos:
    default_front_matter_template: productos
upload_dir: ''
public_path: https://res.cloudinary.com/novatec
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
version: '0.26'
