---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/familias
  label: Familias
  create: all
  match: "**/*"
- type: directory
  path: content/industrias
  label: Industrias
  create: all
  match: "**/*"
- type: directory
  path: content/marcas
  label: Marcas
  create: all
  match: "**/*"
- type: directory
  path: content/novatec-construccion
  label: Novatec construccion
  create: all
  match: "**/*"
- type: directory
  path: content/ncmarcas
  label: Ncmarcas
  create: all
  match: "**/*"
- type: directory
  path: content/noticias
  label: Noticias
  create: all
  match: "**/*"
- type: directory
  path: content/servicio-tecnico
  label: Servicio tecnico
  create: all
  match: "**/*"
- type: directory
  path: content/productos
  label: Productos
  create: all
  match: "**/*"
upload_dir: ''
public_path: https://res.cloudinary.com/novatec
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
version: '0.26'
