---
label: productos
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: id
  label: Id
  type: text
  hidden: false
  default: ''
- name: marcas
  label: Marcas
  type: tag_list
  hidden: false
  default: ''
- name: familias
  label: Familias
  type: tag_list
  hidden: false
  default: ''
- name: industrias
  label: Industrias
  type: tag_list
  hidden: false
  default: ''
- name: imagen
  label: Imagen
  type: file
  hidden: false
  default: ''
- name: catalogo
  label: Catalogo
  type: text
  hidden: false
  default: ''
- name: meta_description
  label: Meta description
  type: text
  hidden: false
  default: ''
- name: meta_keywords
  label: Meta keywords
  type: text
  hidden: false
  default: ''
- name: weight
  label: Weight
  type: text
  hidden: false
  default: ''
- name: taxonomyCover
  label: Taxonomycover
  type: boolean
  hidden: false
  default: ''
- name: type
  label: Type
  type: text
  hidden: false
  default: ''
- name: titulo
  label: Titulo
  type: text
  hidden: false
  default: ''
- name: categoria
  label: Categoria
  type: text
  hidden: false
  default: ''
